### ISSUE TITLE
Cannot read property 'assetsByChunkName' of null

### ISSUE THREAD

**Issue by tommyJS** [thereactivestack/kickstart-simple#25]
Hi All,

When I try to use SSR, then I have the following error in stack trace:
```
W20151101-20:33:58.974(1)? (STDERR) Warning: Each child in an array or iterator should have a unique "key" prop. Check the React.render call using <div>. See https://fb.me/react-warning-keys for more information.
W20151101-20:33:58.984(1)? (STDERR) Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Menu. See https://fb.me/react-warning-keys for more information.
W20151101-20:33:58.993(1)? (STDERR) Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Languages. See https://fb.me/react-warning-keys for more information.
W20151101-20:33:59.108(1)? (STDERR) TypeError: Cannot read property 'assetsByChunkName' of null
W20151101-20:33:59.108(1)? (STDERR)     at ServerResponse.ReactRouterSSR.Run.Meteor.bindEnvironment.WebApp.connectHandlers.use.Meteor.bindEnvironment.res.write (packages/reactrouter_react-router-ssr/lib/server.jsx.js:141:1)
W20151101-20:33:59.109(1)? (STDERR)     at Object.onListeningCallbacks [as handle] (packages/webapp/webapp_server.js:708:1)
W20151101-20:33:59.109(1)? (STDERR)     at next (/home/tommyjs/.meteor/packages/webapp/.1.2.2.1x3aeuk++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
W20151101-20:33:59.109(1)? (STDERR)     at next (/home/tommyjs/.meteor/packages/webapp/.1.2.2.1x3aeuk++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:192:9)
W20151101-20:33:59.110(1)? (STDERR)     at next (/home/tommyjs/.meteor/packages/webapp/.1.2.2.1x3aeuk++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:127:23)
W20151101-20:33:59.110(1)? (STDERR)     at ReactRouterSSR.Run (packages/reactrouter_react-router-ssr/lib/server.jsx.js:163:1)
```

What should I do? Have you ever met this error?

**Comment by eXon** [comment]
Not sure what you have tried. Have you started from a fresh clone? What have you changed?

**Comment by yched** [comment]
Same here. Fresh clone, just commented out the "if production" in entry/server/entry.js to enable SSR on my local setup :

```js
import 'TodoApp/todo-methods';
import 'TodoApp/server/todo-publications';

// Do server-rendering only in proudction mode
//if (process.env.NODE_ENV === 'production') {
  // Load Webpack infos for SSR
  ReactRouterSSR.LoadWebpackStats(WebpackStats);

  require('../client/routes');
//} else {
// ...
//}
```

**Comment by yched** [comment]
Works if I comment out the ```ReactRouterSSR.LoadWebpackStats(WebpackStats);``` line as well

**Comment by eXon** [comment]
You can also do 

```sh
meteor run --production
meteor build
mup deploy
```

You don't need to set an environment variable :)

**Comment by yched** [comment]
Merci ;-)
