### ISSUE TITLE
Just cloned, can't run

### ISSUE THREAD

**Issue by satyavh** [thereactivestack/kickstart-simple#29]
```
➜  React Kickstart simple  meteor -p 3060
[[[[[ ~/Development/React Kickstart simple ]]]]]

=> Started proxy.
=> Started MongoDB.
Installing NPM dependencies for the web bundle...
/bin/sh: /Users/satya/Development/React: No such file or directory
Installing NPM dependencies for the server bundle...
/bin/sh: /Users/satya/Development/React: No such file or directory
=> Errors prevented startup:

   While processing files with webpack:webpack (for target web.browser):
   plugin/WebpackCompiler.js:167:11: An error occured while installing your NPM dependencies.
   at runNpmInstall (plugin/WebpackCompiler.js:167:11)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)


   While processing files with webpack:webpack (for target os.osx.x86_64):
   plugin/WebpackCompiler.js:167:11: An error occured while installing your NPM dependencies.
   at runNpmInstall (plugin/WebpackCompiler.js:167:11)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)
```

Quite a vague error, what now?

**Comment by eXon** [comment]
This is weird. Is it happening if you run on the default port 3000?

On what OS / version are you?

**Comment by satyavh** [comment]
No that doesn't change anything

OSX 10.10.5 (14F27)

**Comment by satyavh** [comment]
It's correct that `/Users/satya/Development/React` doesn't exist

**Comment by harisvsulaiman** [comment]
i too have this problem.

**Comment by harisvsulaiman** [comment]
turns out node cannot be found
i have been using nvm.

**Comment by harisvsulaiman** [comment]
Here is what i did .
nvm use 5.0
then cd the directory and meteor run

**Comment by eXon** [comment]
I'm not sure what you are doing wrong. I just cloned it in a fresh directory and it works fine for me and a lot of people.

Do you have any details on your setup that can be helpful to reproduce?

**Comment by harisvsulaiman** [comment]
@eXon  i got it working as above.
##i had nvm setup so , i had to set node  version each time.
