### ISSUE TITLE
Error starting meteor with freshly cloned repo

### ISSUE THREAD

**Issue by copleykj** [thereactivestack/kickstart-simple#37]
Cloned the repository and tried to run `meteor`, however I get the following error

```
Started MongoDB.
Errors prevented startup:

While processing files with webpack:webpack (for target web.browser):
plugin/WebpackCompiler.js:169:11: An error occured while installing your NPM dependencies.
  at runNpmInstall (plugin/WebpackCompiler.js:169:11)
  at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)


While processing files with webpack:webpack (for target os.linux.x86_64):
plugin/WebpackCompiler.js:169:11: An error occured while installing your NPM dependencies.
  at runNpmInstall (plugin/WebpackCompiler.js:169:11)
  at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)


Your application has errors. Waiting for file change.
```

**Comment by daslicht** [comment]
same here:
```
=> Errors prevented startup:                  
   
   While processing files with webpack:webpack (for target web.browser):
   plugin/WebpackCompiler.js:169:11: An error occured while installing your NPM
   dependencies.
   at runNpmInstall (plugin/WebpackCompiler.js:169:11)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)
   
   
   While processing files with webpack:webpack (for target os.osx.x86_64):
   plugin/WebpackCompiler.js:169:11: An error occured while installing your NPM
   dependencies.
   at runNpmInstall (plugin/WebpackCompiler.js:169:11)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)
   
   
=> Your application has errors. Waiting for file change.
```

**Comment by daslicht** [comment]
Looks like we have to install NodeJS. After that anything works !

**Comment by copleykj** [comment]
So it looks like this was a node version issue on my end. Linux Mint only has v0.10.25 available through the package manager. Manually installed v4.2.4 and I'm up and running.
