### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-simple#4]
Hi, thanks for this package! I was using the other version of webpack meteor and it's pretty cool. Wanted to give yours a try but on start I receive this error:

```
npm-container: updating npm dependencies -- react-mixin, babel-loader, null-loader, url-loader, file-loader, style-loader, css-loader, sass-loader, style-collector-loader,
webpack-hot-middleware, babel-plugin-react-transform, react-transform-hmr, react-transform-catch-errors, redbox-react...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'exposify' from '/C/Users/Tomas/AppData/Local/.meteor/packages/reactrouter_react-router/0.1.9/npm/'
  at C:\Users\Tomas\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
  at process (C:\Users\Tomas\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
  at ondir (C:\Users\Tomas\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
  at load (C:\Users\Tomas\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
  at onex (C:\Users\Tomas\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
  at C:\Users\Tomas\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
  at Object.oncomplete (fs.js:108:15)
```

**Comment by eXon** [comment]
Have you tried removing `/C/Users/Tomas/AppData/Local/.meteor/packages/reactrouter_react-router/` and build it again?

You will also need to remove node_modules unix symbolic link and create a Windows one.

**Comment by eXon** [comment]
Do you still have this error?

**Comment by petewwa** [comment]
I am getting a similar error:
```
[[[[[ ~/Development/50-GITHUB/91-WebPack/kickstart-simple ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
                                                                                   
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
  at errnoException (net.js:905:11)
  at Server._listen2 (net.js:1043:14)
  at listen (net.js:1065:10)
  at Server.listen (net.js:1139:5)
  at compileDevServer (<runJavaScript-46>:699:37)
  at WebpackCompiler.processFilesForTarget (<runJavaScript-46>:401:7)
```

**Comment by eXon** [comment]
@petewwa this error is unrelated. This means you have something running on port 3500. You can change the devServer port by using devServer.port in your webpack.conf.js

**Comment by eXon** [comment]
I'm closing this. If the error persist let me know,
