### ISSUE TITLE
Error building for production - Symbol not found: _node_module_register

### ISSUE THREAD

**Issue by ArdentKid** [thereactivestack/kickstart-simple#44]
One of my npm dependencies requires "jsdom" and doesn't seem to be getting it when running in production with "meteor run --production":

```
TypeError: Object [object Object] has no method 'jsdom'
W20160127-12:36:21.191(-8)? (STDERR)     at Object.<anonymous> (webpack:///Users/Omid/Development/arka/test/kickstart-simple/.meteor/local/webpack-npm/~/fabric/dist/fabric.js:3521:1)
W20160127-12:36:21.191(-8)? (STDERR)     at Object.<anonymous> (webpack:///Users/Omid/Development/arka/test/kickstart-simple/.meteor/local/webpack-npm/~/react-color-picker/~/tinycolor2/tinycolor.js:879:1)
W20160127-12:36:21.191(-8)? (STDERR)     at e (webpack:///(webpack)/~/node-libs-browser/~/buffer/index.js:1543:1)
W20160127-12:36:21.191(-8)? (STDERR)     at Object.t.__esModule.default (webpack:///Users/Omid/Development/arka/test/kickstart-simple/.meteor/local/webpack-npm/~/classnames/index.js:1:1)
W20160127-12:36:21.191(-8)? (STDERR)     at e (webpack:///(webpack)/~/node-libs-browser/~/buffer/index.js:1543:1)
W20160127-12:36:21.192(-8)? (STDERR)     at Object.t.__esModule.default (webpack:///server.js:72096:56)
W20160127-12:36:21.192(-8)? (STDERR)     at e (webpack:///(webpack)/~/node-libs-browser/~/buffer/index.js:1543:1)
W20160127-12:36:21.192(-8)? (STDERR)     at Object.t.__esModule.default (webpack:///Users/Omid/Development/arka/test/kickstart-simple/.meteor/local/webpack-npm/~/fabric/dist/fabric.js:1:1)
W20160127-12:36:21.192(-8)? (STDERR)     at e (webpack:///(webpack)/~/node-libs-browser/~/buffer/index.js:1543:1)
W20160127-12:36:21.192(-8)? (STDERR)     at Object.t.__esModule.default (webpack:///Users/Omid/Development/arka/test/kickstart-simple/.meteor/local/webpack-npm/~/fabric/dist/fabric.js:1:1)
```

So I tried added it to my webpack.packages.json, and used Npm.require("jsdom") in my server entry. But now I'm getting the following error:

```
W20160127-12:32:30.913(-8)? (STDERR) dyld: Symbol not found: _node_module_register
W20160127-12:32:30.914(-8)? (STDERR)   Referenced from: /Users/Omid/Development/arka/test/kickstart-simple/.meteor/local/webpack-npm/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
W20160127-12:32:30.914(-8)? (STDERR)   Expected in: dynamic lookup
```
Can anyone shed some light on this issue?

**Comment by eXon** [comment]
Have you tried using `meteorhacks:npm` for jsdom?

**Comment by eXon** [comment]
In 1.0 you'll be able to use jsdom without any problem.
