### ISSUE TITLE
!! BUILD ERROR !! 

### ISSUE THREAD

**Issue by MaxArrowhead** [thereactivestack/kickstart-simple#45]
Using:
Windows 10
npm version: 3.6.0
node version: 4.2.6

error during build (typing "meteor" in cmd):
=> Errors prevented startup:

While processing files with webpack:webpack (for target web.browser):
plugin/WebpackCompiler.js:169:11: An error occured while installing your NPM
at runNpmInstall (plugin/WebpackCompiler.js:169:11)
at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)

While processing files with webpack:webpack (for target os.windows.x86_32):
plugin/WebpackCompiler.js:169:11: An error occured while installing your NPM
at runNpmInstall (plugin/WebpackCompiler.js:169:11)
at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)

=> Your application has errors. Waiting for file change.

I already did "meteor update" and updated some packages to the newest version.
my node and npm versions are the latest.

Please help, I have no idea where to start.

**Comment by MaxArrowhead** [comment]
please delete this,  issue its a double post.
